# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('locations_found', models.CharField(blank=True, max_length=1024, null=True)),
                ('rupee_val', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemQuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('quest_name', models.CharField(max_length=1024)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TimezoneChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hours', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=1024)),
                ('fname', models.CharField(max_length=1024)),
                ('lname', models.CharField(max_length=1024)),
                ('email', models.EmailField(max_length=254)),
                ('optIn', models.BooleanField(default=False)),
                ('tc_agree_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('salt', models.CharField(editable=False, max_length=1024)),
                ('hash', models.CharField(editable=False, max_length=1024)),
                ('createdDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updatedDate', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('lastLoginDate', models.DateTimeField(editable=False, null=True)),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('userTimezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.TimezoneChart')),
            ],
        ),
        migrations.CreateModel(
            name='UserQuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.Quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.User')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='botw.Set'),
        ),
        migrations.AddField(
            model_name='quest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.Type'),
        ),
        migrations.AddField(
            model_name='itemquest',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.Quest'),
        ),
    ]
