# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botw', '0002_amiibo_useramiibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amiibo',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='useramiibo',
            name='amiibo_id',
        ),
        migrations.RemoveField(
            model_name='useramiibo',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Amiibo',
        ),
        migrations.DeleteModel(
            name='UserAmiibo',
        ),
    ]
