# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('botw', '0003_auto_20171019_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amiibo',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('amiibo_name', models.CharField(max_length=1024)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.Set')),
            ],
        ),
        migrations.CreateModel(
            name='UserAmiibo',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('bought', models.BooleanField(default=False)),
                ('amiibo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.Amiibo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botw.User')),
            ],
        ),
    ]
