# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('botw', '0004_auto_20170821_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezonechart',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='createdDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='hash',
            field=models.CharField(editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastLoginDate',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='tc_agree_timestamp',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updatedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
