# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botw', '0006_auto_20170822_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rupee_val',
            field=models.IntegerField(null=True),
        ),
    ]
