# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botw', '0008_auto_20170822_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
