# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botw', '0009_auto_20170822_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='group',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
