# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botw', '0011_auto_20170823_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemquest',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='itemquest',
            old_name='quest_id',
            new_name='quest',
        ),
    ]
